---
image: node
build:
  stage: build
  variables:
    PUBLIC_URL: /test
  script:
    - npm install
    - npm run build
  tags:
    - general
  artifacts:
    paths:
      - build
pages:
  stage: deploy
  dependencies:
    - build
  script:
    - rm -rf public
    - mv build public
  tags:
    - general
  artifacts:
    paths:
      - public
  only:
    - main
